name: Deploy Quartz Site to GitHub Pages

on:
  push:
    branches:
      - main # Имя ветки, при пушах в которую будет запускаться action

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: windows-latest # Использовать среду Windows
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Забрать полную историю коммитов

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x' # Устанавливаем Node.js версии 18.x

      - name: Install dependencies
        run: |
          npm ci # Устанавливаем зависимости согласно lock-файлу

      - name: Build Quartz
        run: |
          npx quartz build # Генерируем статические файлы сайта

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public # Папка с собранными файлами

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1